spring:
  # database
  datasource:
    url: jdbc:mysql://localhost:3306/imdb?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
  # activemq Config    
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    
#    pool:
#      #true表示使用连接池；false时，每发送一条数据创建一个连接
#      enabled: false
#      #连接池最大连接数
#      max-connections: 10
#      #空闲的连接过期时间，默认为30秒
#      idle-timeout: 30000
  # redis
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 10000
        # 连接池中的最大空闲连接 默认 8
        max-idle: 500
        # 连接池中的最小空闲连接 默认 0
        min-idle: 8
        # 空闲时每隔1小时访问一次
        time-between-eviction-runs: 3600000
    # 连接超时时间（毫秒）    
    timeout: 1000